#include "loc.h"

#define ENTRANCE(i, loc, desc) {.index=i} //use macro to strip unwanted info from the binary
//padding  is so that the whole block is aligned in sublime
__attribute__ ((aligned (4)))
const entry_t ref[] = 
{
	ENTRANCE( 0x0000	,"	Deku Tree	                             ", "From Kokiri Forest"                                                 ),
	ENTRANCE( 0x0004	,"	Dodongo's Cavern	                     ", "From Death Mountain Trail"                                          ),
	ENTRANCE( 0x0008	,"	Gerudo Training Grounds	                 ", "From Gerudo Fortress"                                               ),
	ENTRANCE( 0x000C	,"	Forest Temple Boss	                     ", "From Forest Temple"                                                 ),
	ENTRANCE( 0x0010	,"	Water Temple	                         ", "From Lake Hylia"                                                    ),
	ENTRANCE( 0x0014	,"	Lost Scene	                             ", ""                                                                   ),
	ENTRANCE( 0x0018	,"	Action Testing Room	                     ", ""                                                                   ),
	ENTRANCE( 0x001C	,"	Stalfos Middle Room	                     ", ""                                                                   ),
	ENTRANCE( 0x0020	,"	Stalfos Boss Room	                     ", ""                                                                   ),
	ENTRANCE( 0x0024	,"	Item Testing Room	                     ", ""                                                                   ),
	ENTRANCE( 0x0028	,"	Inside Jabu Jabu's Belly	             ", "From Zora's Fountain"                                               ),
	ENTRANCE( 0x002D	,"	Royal Family's Tomb	                     ", "From Graveyard"                                                     ),
	ENTRANCE( 0x0033	,"	Market Entrance - Child Day	             ", "From Market"                                                        ),
	ENTRANCE( 0x0034	,"	Market Entrance - Child Night	         ", "From Market"                                                        ),	
	ENTRANCE( 0x0035	,"	Market Entrance - Adult	                 ", "From Market"                                                        ),
	ENTRANCE( 0x0036	,"	Market Entrance - Adult	                 ", "From Market"                                                        ),
	ENTRANCE( 0x0037	,"	Shadow Temple	                         ", "From Graveyard"                                                     ),
	ENTRANCE( 0x003B	,"	Shooting Gallery	                     ", "From Kakariko Village"                                              ),
//	ENTRANCE( 0x003F	,"	Grottos	                                 ", "Default"                                                            ), 			removed form pool cause grotto randomization isn't supported yet
	ENTRANCE( 0x0043	,"	Lakeside Laboratory	                     ", "From Lake Hylia"                                                    ),
	ENTRANCE( 0x0047	,"	Dark Link Testing Area	                 ", ""                                                                   ),
	ENTRANCE( 0x004B	,"	Grave with Shield	                     ", "Hylian Shield Chest from Graveyard"                                 ),
	ENTRANCE( 0x004F	,"	Lon Lon Ranch Buildings	                 ", "Talon's House from Lon Lon Ranch"                                   ),
//	ENTRANCE( 0x0053	,"	Temple of Time	                         ", "From Outside Temple of Time"                                        ),				removed as a simple way to ensure DoT can always be open (if needed can always exit and reenter)
	ENTRANCE( 0x0063	,"	Treasure Box Shop	                     ", "From Market"                                                        ),
	ENTRANCE( 0x0067	,"	Back Alley - Day	                     ", "Right side of alley, from door from Back Alley Village House"       ),
	ENTRANCE( 0x0068	,"	Back Alley - Night	                     ", "Right side of alley, from door from Back Alley Village House"       ),
	ENTRANCE( 0x0069	,"	Back Alley - Day	                     ", "Right side of alley, from door from Back Alley Village House"       ),
	ENTRANCE( 0x006A	,"	Back Alley - Night	                     ", "Right side of alley, from door from Back Alley Village House"       ),
	ENTRANCE( 0x006B	,"	Chamber of Sages	                     ", ""                                                                   ),
	ENTRANCE( 0x0072	,"	Granny's Potion Shop	                 ", "From Kakariko Village"                                              ),
	ENTRANCE( 0x0076	,"	Beta Castle Courtyard	                 ", ""                                                                   ),
	ENTRANCE( 0x007A	,"	Castle Courtyard - Day	                 ", "Castle Crawlspace"                                                  ),
	ENTRANCE( 0x007E	,"	Lots 'o Pots	                         ", "From Market Entrance"                                               ),
	ENTRANCE( 0x0082	,"	Spirit Temple	                         ", "From Desert Colossus"                                               ),			
	ENTRANCE( 0x0088	,"	Ice Cavern	                             ", "From Zora's Fountain"                                               ),
	ENTRANCE( 0x008D	,"	Spirit Temple Boss	                     ", "From Spirit Temple"                                                 ),
	ENTRANCE( 0x0094	,"	Collision Testing Arena	                 ", ""                                                                   ),
	ENTRANCE( 0x0098	,"	Bottom of the Well	                     ", "From Kakariko Village"                                              ),
	ENTRANCE( 0x009C	,"	House of Twins	                         ", "From Kokiri Forest"                                                 ),
	ENTRANCE( 0x00A0	,"	Cutscene Map	                         ", ""                                                                   ),
	ENTRANCE( 0x00AD	,"	Back Alley - Day	                     ", "Right Entrance from Market"                                         ),
	ENTRANCE( 0x00AE	,"	Back Alley - Night	                     ", "Right Entrance from Market"                                         ),
	ENTRANCE( 0x00AF	,"	Back Alley - Day	                     ", "Right Entrance from Market"                                         ),
	ENTRANCE( 0x00B0	,"	Back Alley - Night	                     ", "Right Entrance from Market"                                         ),
	ENTRANCE( 0x00B1	,"	Market - Child Day	                     ", "From Market Entrance"                                               ),
	ENTRANCE( 0x00B2	,"	Market - Child Night	                 ", "From Market Entrance"                                               ),
	ENTRANCE( 0x00B3	,"	Market - Adult	                         ", "From Market Entrance"                                               ),
	ENTRANCE( 0x00B4	,"	Market - Adult	                         ", "From Market Entrance"                                               ),
	ENTRANCE( 0x00B5	,"	Market - Child Day	                     ", "From Market Entrance"                                               ),
	ENTRANCE( 0x00B6	,"	Depth Test	                             ", ""                                                                   ),
	ENTRANCE( 0x00B7	,"	Bazaar	                                 ", "From Kakariko Village"                                              ),
//	ENTRANCE( 0x00BB	,"	Link's House	                         ", "Bed Entrance from Savewarp"                                         ),				because a hook from savewarp hasn't been found yet
	ENTRANCE( 0x00C1	,"	Kokiri Shop	                             ", "From Kokiri Forest"                                                 ),
	ENTRANCE( 0x00C5	,"	Dodongo's Cavern	                     ", "From Dodongo's Cavern Boss"                                         ),
	ENTRANCE( 0x00C9	,"	Know-it-all Brothers	                 ", "From Kokiri Forest"                                                 ),
	ENTRANCE( 0x00CD	,"	Hyrule Field	                         ", "Various After Zelda Escape, 2nd+ Impa Escort"                       ),
	ENTRANCE( 0x00DB	,"	Kakariko Village	                     ", "From Hyrule Field"                                                  ),
	ENTRANCE( 0x00E4	,"	Graveyard	                             ", "From Kakariko Village"                                              ),
	ENTRANCE( 0x00EA	,"	Zora River	                             ", "Land Entrance from Hyrule Field"                                    ),
	ENTRANCE( 0x00EE	,"	Kokiri Forest	                         ", "Various After Forest Medallion Cutscene"                            ),
	ENTRANCE( 0x00FC	,"	Sacred Forest Meadow	                 ", "From Lost Woods"                                                    ),
	ENTRANCE( 0x0102	,"	Lake Hylia	                             ", "From Hyrule Field"                                                  ),
	ENTRANCE( 0x0108	,"	Zora's Domain	                         ", "From Zora River"                                                    ),
	ENTRANCE( 0x010E	,"	Zora's Fountain	                         ", "Sapphire Cutscene Entrance"                                         ),
	ENTRANCE( 0x0117	,"	Gerudo Valley	                         ", "From Hyrule Field"                                                  ),
	ENTRANCE( 0x011E	,"	Lost Woods	                             ", "From Kokiri Forest"                                                 ),
	ENTRANCE( 0x0123	,"	Desert Colossus	                         ", "From Haunted Wasteland"                                             ),
	ENTRANCE( 0x0129	,"	Gerudo Fortress	                         ", "From Gerudo Valley"                                                 ),
	ENTRANCE( 0x0130	,"	Haunted Wasteland	                     ", "From Gerudo Fortress"                                               ),
	ENTRANCE( 0x0134	,"	Tower Collapse Interior	                 ", "Bottom of Boss Room Tower Collapse Exterior Lower"                  ),
	ENTRANCE( 0x0138	,"	Hyrule Castle	                         ", "From Market Entrance"                                               ),
	ENTRANCE( 0x0139	,"	Hyrule Castle	                         ", "From Market Entrance"                                               ),
	ENTRANCE( 0x013A	,"	Ganon's Castle	                         ", "From Market Entrance"                                               ),
	ENTRANCE( 0x013B	,"	Ganon's Castle	                         ", "From Market Entrance"                                               ),
	ENTRANCE( 0x013C	,"	Ganon's Castle	                         ", "From Market Entrance"                                               ),
	ENTRANCE( 0x013D	,"	Death Mountain Trail	                 ", "From Kakariko Village"                                              ),
	ENTRANCE( 0x0147	,"	Death Mountain Crater	                 ", "From Death Mountain Trail"                                          ),
	ENTRANCE( 0x014D	,"	Goron City	                             ", "From Death Mountain Trail"                                          ),
	ENTRANCE( 0x0153	,"	Zora's Domain	                         ", "Eyeball Frog Timeout"                                               ),
	ENTRANCE( 0x0157	,"	Lon Lon Ranch	                         ", "From Hyrule Field"                                                  ),
	ENTRANCE( 0x0165	,"	Fire Temple	                             ", "From Death Mountain Crater"                                         ),
	ENTRANCE( 0x0169	,"	Forest Temple	                         ", "From Sacred Forest Meadow"                                          ),
	ENTRANCE( 0x016D	,"	Shooting Gallery	                     ", "From Market Entrance"                                               ),
	ENTRANCE( 0x0171	,"	Outside Temple of Time - Child Day	     ", "From Market Entrance"                                               ),
	ENTRANCE( 0x0172	,"	Outside Temple of Time - Child Night	 ", "From Market Entrance"                                               ),
	ENTRANCE( 0x0175	,"	Fire Temple	                             ", "Outside Boss Door Fire Temple Boss Secret Map #0"                   ),
	ENTRANCE( 0x0179	,"	Tower Collapse Interior	                 ", "Bottom of Boss Room Tower Collapse Exterior Higher"                 ),
	ENTRANCE( 0x017D	,"	Hyrule Field	                         ", "From Kakariko Village"                                              ),
	ENTRANCE( 0x0181	,"	Hyrule Field	                         ", "Zora River Land"                                                    ),
	ENTRANCE( 0x0185	,"	Hyrule Field	                         ", "From Lost Woods"                                                    ),
	ENTRANCE( 0x0189	,"	Hyrule Field	                         ", "From Lake Hylia"                                                    ),
	ENTRANCE( 0x018D	,"	Hyrule Field	                         ", "From Gerudo Valley"                                                 ),
	ENTRANCE( 0x0191	,"	Kakariko Village	                     ", "From Death Mountain Trail"                                          ),
	ENTRANCE( 0x0195	,"	Kakariko Village	                     ", "From Graveyard"                                                     ),
	ENTRANCE( 0x0199	,"	Zora River	                             ", "Dropped from top of Waterfall"                                      ),
	ENTRANCE( 0x019D	,"	Zora River	                             ", "From Zora's Domain"                                                 ),
	ENTRANCE( 0x01A1	,"	Zora's Domain	                         ", "From Zora's Fountain"                                               ),
	ENTRANCE( 0x01A5	,"	Gerudo Valley	                         ", "Thrown out of Gerudo Fortress when caught without a usable hookshot"),
	ENTRANCE( 0x01A9	,"	Lost Woods	                             ", "From Sacred Forest Meadow"                                          ),
	ENTRANCE( 0x01AD	,"	Lost Woods	                             ", "Mushroom Timeout (Adult)"                                           ),
	ENTRANCE( 0x01B1	,"	Lost Woods	                             ", "Start from the tree opposite of the main entrance"                  ),
	ENTRANCE( 0x01B5	,"	Tower Collapse Interior	                 ", "Burning Rocks Tower Collapse Exterior Higher"                       ),
	ENTRANCE( 0x01B9	,"	Death Mountain Trail	                 ", "From Goron City"                                                    ),
	ENTRANCE( 0x01BD	,"	Death Mountain Trail	                 ", "From Death Mountain Crater"                                         ),
	ENTRANCE( 0x01C1	,"	Goron City	                             ", "From Death Mountain Crater"                                         ),
	ENTRANCE( 0x01C5	,"	Lakeside Laboratory	                     ", "Possibly Eyedrops Timeout"                                          ),
	ENTRANCE( 0x01C9	,"	Tower Collapse Exterior	                 ", "Tower Collapse Interior Stalfos Room (Higher)"                      ),
	ENTRANCE( 0x01CD	,"	Market - Child Day	                     ", "From Shooting Gallery"                                              ),
	ENTRANCE( 0x01CE	,"	Market - Child Night	                 ", "From Shooting Gallery"                                              ),
	ENTRANCE( 0x01CF	,"	Market - Adult	                         ", "From Shooting Gallery"                                              ),
	ENTRANCE( 0x01D0	,"	Market - Adult	                         ", "From Shooting Gallery"                                              ),
	ENTRANCE( 0x01D1	,"	Market - Child Day	                     ", "From Happy Mask Shop"                                               ),
	ENTRANCE( 0x01D2	,"	Market - Child Night	                 ", "From Happy Mask Shop"                                               ),
	ENTRANCE( 0x01D3	,"	Market - Adult	                         ", "From Happy Mask Shop"                                               ),
	ENTRANCE( 0x01D4	,"	Market - Adult	                         ", "From Happy Mask Shop"                                               ),
	ENTRANCE( 0x01D5	,"	Market - Child Day	                     ", "From Treasure Box Shop"                                             ),
	ENTRANCE( 0x01D6	,"	Market - Child Night	                 ", "From Treasure Box Shop"                                             ),
	ENTRANCE( 0x01D7	,"	Market - Adult	                         ", "From Treasure Box Shop"                                             ),
	ENTRANCE( 0x01D8	,"	Market - Adult	                         ", "From Treasure Box Shop"                                             ),
	ENTRANCE( 0x01D9	,"	Zora River	                             ", "Water Entrance from Hyrule Field"                                   ),
	ENTRANCE( 0x01DD	,"	Zora River	                             ", "From Lost Woods"                                                    ),
	ENTRANCE( 0x01E1	,"	Desert Colossus	                         ", "From Spirit Temple"                                                 ),
	ENTRANCE( 0x01E5	,"	Desert Colossus	                         ", "Spirit Temple Gauntlets Entrance"                                   ),
	ENTRANCE( 0x01E9	,"	Desert Colossus	                         ", "Spirit Temple Mirror Shield Entrance"                               ),
	ENTRANCE( 0x01ED	,"	Desert Colossus	                         ", "After Requiem Cutscene"                                             ),
	ENTRANCE( 0x01F1	,"	Desert Colossus	                         ", "Requiem Entrance"                                                   ),
	ENTRANCE( 0x01F5	,"	Desert Colossus	                         ", "Nabooru Capture Cutscene Entrance"                                  ),
	ENTRANCE( 0x01F9	,"	Hyrule Field	                         ", "From Lon Lon Ranch"                                                 ),
	ENTRANCE( 0x01FD	,"	Hyrule Field	                         ", "From Market Entrance"                                               ),
	ENTRANCE( 0x0201	,"	Kakariko Village	                     ", "From Kakariko Bazaar"                                               ),
	ENTRANCE( 0x0205	,"	Graveyard	                             ", "From Shadow Temple"                                                 ),
	ENTRANCE( 0x0209	,"	Kokiri Forest	                         ", "From Deku Tree"                                                     ),
	ENTRANCE( 0x020D	,"	Kokiri Forest	                         ", "Lost Woods Hyrule Bridge"                                           ),
	ENTRANCE( 0x0211	,"	Kokiri Forest	                         ", "From Link's House"                                                  ),
	ENTRANCE( 0x0215	,"	Sacred Forest Meadow	                 ", "From Forest Temple"                                                 ),
	ENTRANCE( 0x0219	,"	Lake Hylia	                             ", "From Gerudo Valley"                                                 ),
	ENTRANCE( 0x021D	,"	Lake Hylia	                             ", "Child spawns you around surface from Water Temple"                  ),
	ENTRANCE( 0x0221	,"	Zora's Fountain	                         ", "From Inside Jabu Jabu's Belly"                                      ),
	ENTRANCE( 0x0225	,"	Zora's Fountain	                         ", "From Zora's Domain"                                                 ),
	ENTRANCE( 0x0229	,"	Gerudo Valley	                         ", "Triggers Fortress Loading Zone"                                     ),
	ENTRANCE( 0x022D	,"	Gerudo Valley	                         ", "From Gerudo Fortress"                                               ),
	ENTRANCE( 0x0231	,"	Gerudo Fortress	                         ", "From Thieves' Hideout (B)"                                          ),
	ENTRANCE( 0x0235	,"	Gerudo Fortress	                         ", "From Thieves' Hideout (C)"                                          ),
	ENTRANCE( 0x0239	,"	Gerudo Fortress	                         ", "From Thieves' Hideout (D)"                                          ),
	ENTRANCE( 0x023D	,"	Hyrule Castle	                         ", "From Castle Courtyard"                                              ),
	ENTRANCE( 0x023E	,"	Hyrule Castle	                         ", "From Castle Courtyard"                                              ),
	ENTRANCE( 0x023F	,"	Ganon's Castle	                         ", "From Inside Ganon's Castle"                                         ),
	ENTRANCE( 0x0240	,"	Ganon's Castle	                         ", "From Inside Ganon's Castle"                                         ),
	ENTRANCE( 0x0241	,"	Hyrule Castle	                         ", "From Castle Courtyard"                                              ),
	ENTRANCE( 0x0242	,"	Death Mountain Trail	                 ", "From Dodongo's Cavern"                                              ),
	ENTRANCE( 0x0246	,"	Death Mountain Crater	                 ", "From Goron City"                                                    ),
	ENTRANCE( 0x024A	,"	Death Mountain Crater	                 ", "From Fire Temple"                                                   ),
	ENTRANCE( 0x024E	,"	Forest Temple	                         ", "Outside Boss Door Forest Temple Boss Secret Map #0"                 ),
	ENTRANCE( 0x0252	,"	Deku Tree	                             ", "From Deku Tree Boss"                                                ),
	ENTRANCE( 0x0256	,"	Tower Collapse Interior	                 ", "Burning Rocks Tower Collapse Exterior Lower"                        ),
	ENTRANCE( 0x025A	,"	Market - Child Day	                     ", "From Castle"                                                        ),
	ENTRANCE( 0x025B	,"	Market - Child Night	                 ", "From Castle"                                                        ),
	ENTRANCE( 0x025C	,"	Market - Adult	                         ", "From Ganon's Castle"                                                ),
	ENTRANCE( 0x025D	,"	Market - Adult	                         ", "From Ganon's Castle"                                                ),
	ENTRANCE( 0x025E	,"	Market - Child Day	                     ", "From Temple of Time"                                                ),
	ENTRANCE( 0x025F	,"	Market - Child Night	                 ", "From Temple of Time"                                                ),
	ENTRANCE( 0x0260	,"	Market - Adult	                         ", "From Temple of Time"                                                ),
	ENTRANCE( 0x0261	,"	Market - Adult	                         ", "From Temple of Time"                                                ),
	ENTRANCE( 0x0262	,"	Market - Child Day	                     ", "Back Alley (Right)"                                                 ),
	ENTRANCE( 0x0263	,"	Market - Child Night	                 ", "Back Alley (Right)"                                                 ),
	ENTRANCE( 0x0264	,"	Market - Adult	                         ", "Back Alley (Right)"                                                 ),
	ENTRANCE( 0x0265	,"	Market - Adult	                         ", "Back Alley (Right)"                                                 ),
	ENTRANCE( 0x0266	,"	Kokiri Forest	                         ", "From Kokiri Shop"                                                   ),
	ENTRANCE( 0x026A	,"	Kokiri Forest	                         ", "From Know-it-all Brothers"                                          ),
	ENTRANCE( 0x026E	,"	Market Entrance - Child Day	             ", "From Lots 'o Pots"                                                  ),
	ENTRANCE( 0x026F	,"	Market Entrance - Child Night	         ", "From Lots 'o Pots"                                                  ),
	ENTRANCE( 0x0270	,"	Market Entrance - Adult	                 ", "From Lots 'o Pots"                                                  ),
	ENTRANCE( 0x0271	,"	Market Entrance - Adult	                 ", "From Lots 'o Pots"                                                  ),
	ENTRANCE( 0x0272	,"	Link's House	                         ", "From Kokiri Forest"                                                 ),
	ENTRANCE( 0x0276	,"	Market Entrance - Child Day	             ", "From Hyrule Field"                                                  ),
	ENTRANCE( 0x0277	,"	Market Entrance - Child Night	         ", "From Hyrule Field"                                                  ),
	ENTRANCE( 0x0278	,"	Market Entrance - Adult	                 ", "From Hyrule Field"                                                  ),
	ENTRANCE( 0x0279	,"	Market Entrance - Adult	                 ", "From Hyrule Field"                                                  ),
	ENTRANCE( 0x027A	,"	Hyrule Field	                         ", "Positioned near Lake Hylia"                                         ),
	ENTRANCE( 0x027E	,"	Hyrule Field	                         ", "Owl Drop Spot from Lake Hylia"                                      ),
	ENTRANCE( 0x0282	,"	Hyrule Field	                         ", "Unused Location"                                                    ),
	ENTRANCE( 0x0286	,"	Kokiri Forest	                         ", "From Lost Woods"                                                    ),
	ENTRANCE( 0x028A	,"	Hyrule Field	                         ", "Lon Lon Ranch Southern Fence Jump"                                  ),
	ENTRANCE( 0x028E	,"	Hyrule Field	                         ", "Lon Lon Ranch Western Fence Jump"                                   ),
	ENTRANCE( 0x0292	,"	Hyrule Field	                         ", "Lon Lon Ranch Eastern Fence Jump"                                   ),
	ENTRANCE( 0x0296	,"	Castle Courtyard - Day	                 ", "From Zelda's Courtyard"                                             ),
	ENTRANCE( 0x029A	,"	Back Alley - Day	                     ", "Left Entrance from Market"                                          ),
	ENTRANCE( 0x029B	,"	Back Alley - Night	                     ", "Left Entrance from Market"                                          ),
	ENTRANCE( 0x029C	,"	Back Alley - Day	                     ", "Left Entrance from Market"                                          ),
	ENTRANCE( 0x029D	,"	Back Alley - Night	                     ", "Left Entrance from Market"                                          ),
	ENTRANCE( 0x029E	,"	Market - Child Day	                     ", "Back Alley (Left)"                                                  ),
	ENTRANCE( 0x029F	,"	Market - Child Night	                 ", "Back Alley (Left)"                                                  ),
	ENTRANCE( 0x02A0	,"	Market - Adult	                         ", "Back Alley (Left)"                                                  ),
	ENTRANCE( 0x02A1	,"	Market - Adult	                         ", "Back Alley (Left)"                                                  ),
	ENTRANCE( 0x02A2	,"	Market - Child Day	                     ", "From Market Potion Shop"                                            ),
	ENTRANCE( 0x02A3	,"	Market - Child Night	                 ", "From Potion Shop"                                                   ),
	ENTRANCE( 0x02A4	,"	Market - Adult	                         ", "From Potion Shop"                                                   ),
	ENTRANCE( 0x02A5	,"	Market - Adult	                         ", "From Potion Shop"                                                   ),
	ENTRANCE( 0x02A6	,"	Kakariko Village	                     ", "From Bottom of the Well"                                            ),
	ENTRANCE( 0x02AA	,"	Gerudo Fortress	                         ", "From Thieves' Hideout (E)"                                          ),
	ENTRANCE( 0x02AE	,"	Lon Lon Ranch	                         ", "Epona's Song Cutscene"                                              ),
//	ENTRANCE( 0x02B2	,"	Shadow Temple	                         ", "Outside Boss Door"                                                  ),				crashes
	ENTRANCE( 0x02B6	,"	Shadow Temple	                         ", "Shadow Temple Boss Secret Map #0"                                   ),
	ENTRANCE( 0x02BA	,"	Gerudo Fortress	                         ", "From Thieves' Hideout (K)"                                          ),
	ENTRANCE( 0x02BE	,"	Gerudo Fortress	                         ", "From Thieves' Hideout (J)"                                          ),
	ENTRANCE( 0x02C2	,"	Gerudo Fortress	                         ", "From Thieves' Hideout (H)"                                          ),
	ENTRANCE( 0x02C6	,"	Gerudo Fortress	                         ", "From Thieves' Hideout (I)"                                          ),
	ENTRANCE( 0x02CA	,"	Temple of Time	                         ", "Pull or Place Master Sword"                                         ),
	ENTRANCE( 0x02CE	,"	Chamber of Sages	                     ", "??? (Forest Medallion?)"                                            ),
	ENTRANCE( 0x02D2	,"	Gerudo Fortress	                         ", "From Thieves' Hideout (F)"                                          ),
	ENTRANCE( 0x02D6	,"	Gerudo Fortress	                         ", "From Thieves' Hideout (G)"                                          ),
	ENTRANCE( 0x02DA	,"	Gerudo Fortress	                         ", "From Thieves' Hideout (M)"                                          ),
	ENTRANCE( 0x02DE	,"	Gerudo Fortress	                         ", "From Thieves' Hideout (N)"                                          ),
	ENTRANCE( 0x02E2	,"	Lon Lon Ranch	                         ", "Near South Gate"                                                    ),
	ENTRANCE( 0x02E6	,"	Lon Lon Ranch	                         ", "Near West Gate"                                                     ),
	ENTRANCE( 0x02EA	,"	Shooting Gallery	                     ", "From Kakariko Village"                                              ),
	ENTRANCE( 0x02EE	,"	Sacred Forest Meadow	                 ", "From Lost Woods"                                                    ),
	ENTRANCE( 0x02EF	,"	Cutscene Map	                         ", ""                                                                   ),
	ENTRANCE( 0x02F0	,"	Shooting Gallery	                     ", "From Kakariko Village"                                              ),
	ENTRANCE( 0x02F5	,"	Spirit Temple	                         ", "Boss Room Entrance from Spirit Temple Boss"                         ),
	ENTRANCE( 0x02F9	,"	Stables	                                 ", "From Lon Lon Ranch"                                                 ),
	ENTRANCE( 0x02FD	,"	Kakariko Village House	                 ", "Boss's House from Kakariko Village"                                 ),
	ENTRANCE( 0x0301	,"	Inside Jabu Jabu's Belly Boss	         ", "From Inside Jabu Jabu's Belly"                                      ),
	ENTRANCE( 0x0305	,"	Fire Temple Boss	                     ", "From Fire Temple"                                                   ),
	ENTRANCE( 0x0309	,"	Lake Hylia	                             ", "From Fishing Pond"                                                  ),
	ENTRANCE( 0x030D	,"	Gravekeeper's Hut	                     ", "From Graveyard"                                                     ),
	ENTRANCE( 0x0311	,"	Hyrule Field	                         ", "Zora River Water"                                                   ),
	ENTRANCE( 0x0315	,"	Great Fairy Fountain	                 ", "From Death Mountain Trail"                                          ),
	ENTRANCE( 0x031C	,"	Grave with Redead	                     ", "From Graveyard"                                                     ),
	ENTRANCE( 0x0320	,"	Temple of Time	                         ", "Standing facing away from SoT spot"                                 ),
	ENTRANCE( 0x0324	,"	Temple of Time	                         ", "After pulling the MS for first time?"                               ),
	ENTRANCE( 0x0328	,"	Zora's Domain	                         ", "From Lake Hylia"                                                    ),
	ENTRANCE( 0x032C	,"	Tower Collapse Exterior	                 ", "Tower Collapse Interior Boss Room Floor (Lower)"                    ),
	ENTRANCE( 0x0330	,"	Tower Collapse Exterior	                 ", "Tower Collapse Interior Burning Rocks (Higher)"                     ),
	ENTRANCE( 0x0334	,"	Tower Collapse Exterior	                 ", "Tower Collapse Interior Burning Rocks (Lower)"                      ),
	ENTRANCE( 0x0338	,"	Kokiri Forest	                         ", "Spawn on Link's House"                                              ),
	ENTRANCE( 0x033C	,"	Kokiri Forest	                         ", "From House of Twins"                                                ),
	ENTRANCE( 0x0340	,"	Hyrule Castle	                         ", "From Magic Fairy Fountain"                                          ),
	ENTRANCE( 0x0341	,"	Hyrule Castle	                         ", "From Magic Fairy Fountain"                                          ),
	ENTRANCE( 0x0342	,"	Ganon's Castle	                         ", "From Magic Fairy Fountain"                                          ),
	ENTRANCE( 0x0343	,"	Ganon's Castle	                         ", "From Magic Fairy Fountain"                                          ),
	ENTRANCE( 0x0344	,"	Hyrule Castle	                         ", "From Magic Fairy Fountain"                                          ),
	ENTRANCE( 0x0345	,"	Kakariko Village	                     ", "From Cow Heartpiece House (Door)"                                   ),
	ENTRANCE( 0x0349	,"	Kakariko Village	                     ", "Kakariko Village House Boss's House"                                ),
	ENTRANCE( 0x034D	,"	Kakariko Village	                     ", "From Granny's Potion Shop"                                          ),
	ENTRANCE( 0x0351	,"	Kakariko Village	                     ", "? Windmill"                                                         ),
	ENTRANCE( 0x0355	,"	Graveyard	                             ", "From Gravekeeper's Hut"                                             ),
	ENTRANCE( 0x0359	,"	Graveyard	                             ", "? Dampe's Grave"                                                    ),
	ENTRANCE( 0x035D	,"	Graveyard	                             ", "From Grave with Shield"                                             ),
	ENTRANCE( 0x0361	,"	Graveyard	                             ", "From Grave with Redead"                                             ),
	ENTRANCE( 0x0365	,"	Haunted Wasteland	                     ", "From Desert Colossus"                                               ),
//	ENTRANCE( 0x0369	,"	Haunted Wasteland	                     ", "Crashes (Bad Map)"                                                  ),				softlocks
//	ENTRANCE( 0x036D	,"	Small Fairy Fountain	                 ", "From Grotto spot"                                                   ), 			removed form pool cause grotto randomization isn't supported yet
	ENTRANCE( 0x0371	,"	Magic Fairy Fountain	                 ", "From Zora's Fountain"                                               ),
	ENTRANCE( 0x0378	,"	Lon Lon Ranch	                         ", "Ranch House Talon's House"                                          ),
	ENTRANCE( 0x037C	,"	Goron Shop	                             ", "From Goron City"                                                    ),
	ENTRANCE( 0x0380	,"	Zora Shop	                             ", "From Zora's Domain"                                                 ),
	ENTRANCE( 0x0384	,"	Kakariko Potion Shop	                 ", "From Kakariko Village"                                              ),
	ENTRANCE( 0x0388	,"	Market Potion Shop	                     ", "From Market"                                                        ),
	ENTRANCE( 0x038C	,"	Back Alley - Day	                     ", "From Puppy Woman's House"                                           ),
	ENTRANCE( 0x038D	,"	Back Alley - Night	                     ", "From Puppy Woman's House"                                           ),
	ENTRANCE( 0x038E	,"	Back Alley - Day	                     ", "From Puppy Woman's House"                                           ),
	ENTRANCE( 0x038F	,"	Back Alley - Night	                     ", "From Puppy Woman's House"                                           ),
	ENTRANCE( 0x0390	,"	Bombchu Shop	                         ", "??? (Back Alley)"                                                   ),
	ENTRANCE( 0x0394	,"	Zora's Fountain	                         ", "From Great Fairy Fountain"                                          ),
	ENTRANCE( 0x0398	,"	Puppy Woman's House	                     ", "Puppy Woman's House Back Alley (Left)"                              ),
	ENTRANCE( 0x039C	,"	Impa's House	                         ", "From Kakariko Village"                                              ),
	ENTRANCE( 0x03A0	,"	Carpenter's Tent	                     ", "From Gerudo Valley"                                                 ),
	ENTRANCE( 0x03A4	,"	Gerudo Fortress	                         ", "From Thieves' Hideout (L)"                                          ),
	ENTRANCE( 0x03A8	,"	Gerudo Fortress	                         ", "From Gerudo Training Grounds"                                       ),
	ENTRANCE( 0x03AC	,"	Gerudo Fortress	                         ", "From Haunted Wasteland"                                             ),
	ENTRANCE( 0x03B0	,"	Gerudo Fortress	                         ", "After Horseback Archery from Gerudo Fortress"                       ),
	ENTRANCE( 0x03B4	,"	Gerudo Fortress	                         ", "Captured First Time with Hookshot"                                  ),
	ENTRANCE( 0x03B8	,"	Market - Child Day	                     ", "From Bazaar"                                                        ),
	ENTRANCE( 0x03B9	,"	Market - Child Night	                 ", "From Bazaar"                                                        ),
	ENTRANCE( 0x03BA	,"	Market - Adult	                         ", "From Bazaar"                                                        ),
	ENTRANCE( 0x03BB	,"	Market - Adult	                         ", "From Bazaar"                                                        ),
	ENTRANCE( 0x03BC	,"	Market - Child Day	                     ", "From Bombchu Bowling Alley"                                         ),
	ENTRANCE( 0x03BD	,"	Market - Child Night	                 ", "From Bombchu Bowling Alley"                                         ),
	ENTRANCE( 0x03BE	,"	Market - Adult	                         ", "From Bombchu Bowling Alley"                                         ),
	ENTRANCE( 0x03BF	,"	Market - Adult	                         ", "From Bombchu Bowling Alley"                                         ),
	ENTRANCE( 0x03C0	,"	Back Alley - Day	                     ", "From Bombchu Shop"                                                  ),
	ENTRANCE( 0x03C1	,"	Back Alley - Night	                     ", "From Bombchu Shop"                                                  ),
	ENTRANCE( 0x03C2	,"	Back Alley - Day	                     ", "From Bombchu Shop"                                                  ),
	ENTRANCE( 0x03C3	,"	Back Alley - Night	                     ", "From Bombchu Shop"                                                  ),
	ENTRANCE( 0x03C4	,"	Zora's Domain	                         ", "From Zora Shop"                                                     ),
	ENTRANCE( 0x03C8	,"	Lake Hylia	                             ", "Hyrule Field Entrance"                                              ),
	ENTRANCE( 0x03CC	,"	Lake Hylia	                             ", "From Lakeside Laboratory"                                           ),
	ENTRANCE( 0x03D0	,"	Gerudo Valley	                         ", "From Carpenter's Tent"                                              ),
	ENTRANCE( 0x03D4	,"	Zora's Fountain	                         ", "From Ice Cavern"                                                    ),
	ENTRANCE( 0x03D8	,"	Zora's Fountain	                         ", "SE corner facing fallen tree"                                       ),
	ENTRANCE( 0x03DC	,"	Tower Collapse Interior	                 ", "Stalfos Fight Room Tower Collapse Exterior Higher"                  ),
	ENTRANCE( 0x03E0	,"	Tower Collapse Interior	                 ", "Stalfos Fight Room Tower Collapse Exterior Lower"                   ),
	ENTRANCE( 0x03E4	,"	Tower Collapse Interior	                 ", "Staircase Down Tower Collapse Exterior Higher"                      ),
	ENTRANCE( 0x03E8	,"	Kakariko Potion Shop	                 ", "Kakariko"                                                           ),
	ENTRANCE( 0x03EC	,"	Kakariko Potion Shop	                 ", "Back Door from Kakariko Village"                                    ),
	ENTRANCE( 0x03F0	,"	Spirit Temple	                         ", "Desert Colossus Silver Gauntlets Chest"                             ),
	ENTRANCE( 0x03F4	,"	Spirit Temple	                         ", "Desert Colossus Mirror Shield Chest"                                ),
	ENTRANCE( 0x03F8	,"	Spirit Temple	                         ", "Crashes (Bad Map)"                                                  ),
	ENTRANCE( 0x03FC	,"	Goron City	                             ", "From Goron Shop"                                                    ),
	ENTRANCE( 0x0400	,"	Zelda's Courtyard	                     ", "From Castle Courtyard"                                              ),
	ENTRANCE( 0x0407	,"	Inside Jabu Jabu's Belly	             ", "Map 14 Inside Jabu Jabu's Belly Boss Secret Map #0"                 ),
	ENTRANCE( 0x040B	,"	Dodongo's Cavern Boss	                 ", "From Dodongo's Cavern"                                              ),
	ENTRANCE( 0x040F	,"	Deku Tree Boss	                         ", "From Deku Tree"                                                     ),
	ENTRANCE( 0x0413	,"	Shadow Temple Boss	                     ", "From Shadow Temple"                                                 ),
	ENTRANCE( 0x0417	,"	Water Temple Boss	                     ", "From Water Temple"                                                  ),
	ENTRANCE( 0x041B	,"	Ganon's Tower Climb	                     ", "From Inside Ganon's Castle"                                         ),
	ENTRANCE( 0x041F	,"	Ganondorf Boss Room	                     ", "From Ganon's Tower Climb"                                           ),
	ENTRANCE( 0x0423	,"	Water Temple	                         ", "Main Entrance"                                                      ),
	ENTRANCE( 0x0427	,"	Ganon's Tower Climb	                     ", "From Outside Boss Door"                                             ),
	ENTRANCE( 0x042B	,"	Ganon's Tower Climb	                     ", "Facing Boss Key Door"                                               ),
	ENTRANCE( 0x042F	,"	Lon Lon Ranch	                         ", "From Stables"                                                       ),
	ENTRANCE( 0x0433	,"	Mido's House	                         ", "From Kokiri Forest"                                                 ),
	ENTRANCE( 0x0437	,"	Saria's House	                         ", "From Kokiri Forest"                                                 ),
	ENTRANCE( 0x043B	,"	Back Alley Village House	             ", "Back Alley Guy's House Back Alley (Right)"                          ),
	ENTRANCE( 0x043F	,"	Tower Collapse Exterior	                 ", "Death Cutscene from Ganondorf Boss Room"                            ),
	ENTRANCE( 0x0443	,"	Kokiri Forest	                         ", "From Mido's House"                                                  ),
	ENTRANCE( 0x0447	,"	Kokiri Forest	                         ", "From Saria's House"                                                 ),
	ENTRANCE( 0x044B	,"	Kakariko Village	                     ", "From Kakariko Potion Shop"                                          ),
	ENTRANCE( 0x044F	,"	?	                                     ", "Dampe's Grave from Graveyard"                                       ),
	ENTRANCE( 0x0453	,"	?	                                     ", "Windmill from Kakariko Village"                                     ),
	ENTRANCE( 0x0457	,"	Kokiri Forest	                         ", "After Deku Tree Death Cutscene from Kokiri Forest"                  ),
	ENTRANCE( 0x045B	,"	Death Mountain Trail	                 ", "From Great Fairy Fountain"                                          ),
	ENTRANCE( 0x045F	,"	Fishing Pond	                         ", "From Lake Hylia"                                                    ),
	ENTRANCE( 0x0463	,"	Kakariko Village	                     ", "From Shooting Gallery"                                              ),
	ENTRANCE( 0x0467	,"	Inside Ganon's Castle	                 ", "From Castle"                                                        ),
//	ENTRANCE( 0x0472	,"	Outside Temple of Time - Child Day	     ", "From Temple of Time"                                                ),			see above about DoT
//	ENTRANCE( 0x0473	,"	Outside Temple of Time - Child Night	 ", "From Temple of Time"                                                ),			see above about DoT
	ENTRANCE( 0x0476	,"	Hyrule Field	                         ", "Lon Lon Ranch Front Gate Jump"                                      ),
	ENTRANCE( 0x047A	,"	Death Mountain Trail	                 ", "Goron Ruby Cutscene"                                                ),
	ENTRANCE( 0x047E	,"	Hyrule Castle	                         ", "Guard Capture (Outside)"                                            ),
	ENTRANCE( 0x047F	,"	Hyrule Castle	                         ", "Guard Capture (Outside)"                                            ),
	ENTRANCE( 0x0480	,"	Ganon's Castle	                         ", "Crashes (Bad Map)"                                                  ),
	ENTRANCE( 0x0481	,"	Ganon's Castle	                         ", "Crashes (Bad Map)"                                                  ),
	ENTRANCE( 0x0482	,"	Death Mountain Crater	                 ", "From Great Fairy Fountain"                                          ),
	ENTRANCE( 0x0486	,"	Thieves' Hideout	                     ", "From Gerudo Fortress (B)"                                           ),
	ENTRANCE( 0x048A	,"	Thieves' Hideout	                     ", "From Gerudo Fortress (C)"                                           ),
	ENTRANCE( 0x048E	,"	Thieves' Hideout	                     ", "From Gerudo Fortress (D)"                                           ),
	ENTRANCE( 0x0492	,"	Thieves' Hideout	                     ", "From Gerudo Fortress (E)"                                           ),
	ENTRANCE( 0x0496	,"	Thieves' Hideout	                     ", "From Gerudo Fortress (K)"                                           ),
	ENTRANCE( 0x049A	,"	Thieves' Hideout	                     ", "From Gerudo Fortress (J)"                                           ),
	ENTRANCE( 0x049E	,"	Thieves' Hideout	                     ", "From Gerudo Fortress (H)"                                           ),
	ENTRANCE( 0x04A2	,"	Thieves' Hideout	                     ", "From Gerudo Fortress (I)"                                           ),
	ENTRANCE( 0x04A6	,"	Thieves' Hideout	                     ", "From Gerudo Fortress (F)"                                           ),
	ENTRANCE( 0x04AA	,"	Thieves' Hideout	                     ", "From Gerudo Fortress (G)"                                           ),
	ENTRANCE( 0x04AE	,"	Thieves' Hideout	                     ", "From Gerudo Fortress (M)"                                           ),
	ENTRANCE( 0x04B2	,"	Thieves' Hideout	                     ", "From Gerudo Fortress (N)"                                           ),
	ENTRANCE( 0x04B6	,"	Tower Collapse Interior	                 ", "Staircase Down from Tower Collapse Interior Exit"                   ),
	ENTRANCE( 0x04BA	,"	Tower Collapse Exterior	                 ", "Tower Collapse Interior Boss Room Floor (Higher)"                   ),
	ENTRANCE( 0x04BE	,"	Great Fairy Fountain	                 ", "From Death Mountain Crater"                                         ),
	ENTRANCE( 0x04C2	,"	Great Fairy Fountain	                 ", "From Castle"                                                        ),
	ENTRANCE( 0x04C6	,"	Lost Woods	                             ", "??? placed west of Cojiro Guy map"                                  ),
	ENTRANCE( 0x04CA	,"	Lon Lon Ranch	                         ", "Pay Ingo to Ride"                                                   ),
	ENTRANCE( 0x04CE	,"	Lon Lon Ranch	                         ", "Beat Ingo Both Times"                                               ),
	ENTRANCE( 0x04D2	,"	Lost Woods	                             ", "Exit point clockwise from SFM exit"                                 ),
	ENTRANCE( 0x04D6	,"	Lost Woods	                             ", "From Goron City"                                                    ),
	ENTRANCE( 0x04DA	,"	Lost Woods	                             ", "From Zora River"                                                    ),
	ENTRANCE( 0x04DE	,"	Lost Woods	                             ", "From Hyrule Field"                                                  ),
	ENTRANCE( 0x04E2	,"	Goron City	                             ", "From Lost Woods"                                                    ),
	ENTRANCE( 0x04E6	,"	Lake Hylia	                             ", "Beat Water First Time (Sheik)"                                      ),
	ENTRANCE( 0x04EA	,"	Shadow Temple	                         ", ""                                                                   ),
	ENTRANCE( 0x04EE	,"	Kakariko Village	                     ", "From House of Skulltula"                                            ),
	ENTRANCE( 0x04F2	,"	Great Fairy Fountain	                 ", "Leaving puts you at 044B"                                           ),
	ENTRANCE( 0x04F6	,"	Death Mountain Crater	                 ", "Bolero Entrance"                                                    ),
	ENTRANCE( 0x04FA	,"	Hyrule Castle	                         ", "Castle Courtyard Caught by guard"                                   ),
	ENTRANCE( 0x04FB	,"	Hyrule Castle	                         ", "Castle Courtyard Caught by guard"                                   ),
	ENTRANCE( 0x04FC	,"	Ganon's Castle	                         ", "Castle Courtyard Caught by guard"                                   ),
	ENTRANCE( 0x04FD	,"	Ganon's Castle	                         ", "Castle Courtyard Caught by guard"                                   ),
	ENTRANCE( 0x04FE	,"	Hyrule Castle	                         ", "Castle Courtyard Caught by guard"                                   ),
	ENTRANCE( 0x04FF	,"	Kakariko Village	                     ", "Kakariko Potion Shop Back Entrance"                                 ),
	ENTRANCE( 0x0503	,"	?	                                     ", "Windmill After Song of Storms?"                                     ),
	ENTRANCE( 0x0507	,"	Bombchu Bowling Alley	                 ", "From Market"                                                        ),
	ENTRANCE( 0x050B	,"	Graveyard	                             ", "From Royal Family Tomb"                                             ),
	ENTRANCE( 0x050F	,"	Hyrule Field	                         ", "Get Ocarina of Time"                                                ),
	ENTRANCE( 0x0513	,"	Kakariko Village	                     ", "From Nocturne Cutscene"                                             ),
//	ENTRANCE( 0x0517	,"	Ganon Battle	                         ", "From Tower Collapse Interior Exit"                                  ),				ensure that if you can get to ganon
	ENTRANCE( 0x051C	,"	Tower Collapse Exterior	                 ", "Tower Collapse Interior Stalfos Fight (Lower)"                      ),
	ENTRANCE( 0x0520	,"	Beshitu	                                 ", ""                                                                   ),
	ENTRANCE( 0x0524	,"	Tower Collapse Exterior	                 ", "Tower Collapse Interior Stairs"                                     ),
	ENTRANCE( 0x0528	,"	Bombchu Shop	                         ", "Back Alley (Left)"                                                  ),
	ENTRANCE( 0x052C	,"	Bazaar	                                 ", "From Market"                                                        ),
	ENTRANCE( 0x0530	,"	Happy Mask Shop	                         ", "From Market"                                                        ),
	ENTRANCE( 0x0534	,"	Inside Ganon's Castle	                 ", "From Ganon's Tower Climb"                                           ),
	ENTRANCE( 0x0538	,"	Inside Ganon's Castle	                 ", "Clear Forest Trial from Inside Ganon's Castle"                      ),
	ENTRANCE( 0x053C	,"	Inside Ganon's Castle	                 ", "Clear Water Trial from Inside Ganon's Castle"                       ),
	ENTRANCE( 0x0540	,"	Inside Ganon's Castle	                 ", "Clear Shadow Trial from Inside Ganon's Castle"                      ),
	ENTRANCE( 0x0544	,"	Inside Ganon's Castle	                 ", "Clear Fire Trial from Inside Ganon's Castle"                        ),
	ENTRANCE( 0x0548	,"	Inside Ganon's Castle	                 ", "Clear Light Trial from Inside Ganon's Castle"                       ),
	ENTRANCE( 0x054C	,"	Inside Ganon's Castle	                 ", "Clear Spirit Trial from Inside Ganon's Castle"                      ),
	ENTRANCE( 0x0550	,"	House of Skulltula	                     ", "From Kakariko Village"                                              ),
	ENTRANCE( 0x0554	,"	Kakariko Village	                     ", "Owl Drop Spot Death Mountain Crater Owl Teleport"                   ),
	ENTRANCE( 0x0558	,"	Lon Lon Ranch	                         ", "You're too slow!"                                                   ),
	ENTRANCE( 0x055C	,"	Lon Lon Ranch	                         ", "??? (Near Ingo/Malon)"                                              ),
	ENTRANCE( 0x0560	,"	Lake Hylia	                             ", "From Zora's Domain"                                                 ),
	ENTRANCE( 0x0564	,"	Death Mountain Crater	                 ", "From Fire Temple Blue Warp"                                         ),
	ENTRANCE( 0x0568	,"	Graveyard	                             ", "Nocturne Warp"                                                      ),
	ENTRANCE( 0x056C	,"	Tower Collapse Interior Exit	         ", "Tower Collapse Interior Stairs"                                     ),
	ENTRANCE( 0x0570	,"	Thieves' Hideout	                     ", "From Gerudo Fortress (L)"                                           ),
	ENTRANCE( 0x0574	,"	Royal Family's Tomb	                     ", "Sun Song Cutscene"                                                  ),
	ENTRANCE( 0x0578	,"	Magic Fairy Fountain	                 ", "From Castle"                                                        ),
	ENTRANCE( 0x057C	,"	Desert Colossus	                         ", "From Great Fairy Fountain"                                          ),
	ENTRANCE( 0x0580	,"	Graveyard	                             ", "From Shadow Temple Blue Warp"                                       ),
	ENTRANCE( 0x0584	,"	Forest Temple	                         ", "Ceiling Crush room"                                                 ),
	ENTRANCE( 0x0588	,"	Magic Fairy Fountain	                 ", "From Desert Colossus"                                               ),
	ENTRANCE( 0x058C	,"	Temple of Time	                         ", "Temple of Time Light Arrow Cutscene"                                ),
	ENTRANCE( 0x0590	,"	Temple of Time	                         ", "Front of Pedestal"                                                  ),
	ENTRANCE( 0x0594	,"	Hyrule Field	                         ", "After Impa Escort Cutscene"                                         ),
//	ENTRANCE( 0x0598	,"	Grottos	                                 ", "Big Skulltula"                                                      ), 			removed form pool cause grotto randomization isn't supported yet
//	ENTRANCE( 0x059C	,"	Grottos	                                 ", "Heartpiece Scrub"                                                   ), 			removed form pool cause grotto randomization isn't supported yet
//	ENTRANCE( 0x05A0	,"	Grottos	                                 ", "Two Redead"                                                         ), 			removed form pool cause grotto randomization isn't supported yet
//	ENTRANCE( 0x05A4	,"	Grottos	                                 ", "Three Deku Salescrubs"                                              ), 			removed form pool cause grotto randomization isn't supported yet
//	ENTRANCE( 0x05A8	,"	Grottos	                                 ", "Webbed"                                                             ), 			removed form pool cause grotto randomization isn't supported yet
//	ENTRANCE( 0x05AC	,"	Grottos	                                 ", "Octoroc"                                                            ), 			removed form pool cause grotto randomization isn't supported yet
//	ENTRANCE( 0x05B0	,"	Grottos	                                 ", "Two Deku Salescrubs, Closest sells Deku Nut Upgrade"                ), 			removed form pool cause grotto randomization isn't supported yet
//	ENTRANCE( 0x05B4	,"	Grottos	                                 ", "Two Wolfos"                                                         ), 			removed form pool cause grotto randomization isn't supported yet
//	ENTRANCE( 0x05B8	,"	Grottos	                                 ", "Bomb Wall"                                                          ), 			removed form pool cause grotto randomization isn't supported yet
//	ENTRANCE( 0x05BC	,"	Grottos	                                 ", "Two Deku Salescrubs, Closest sells Green Pot"                       ), 			removed form pool cause grotto randomization isn't supported yet
//	ENTRANCE( 0x05C0	,"	Grottos	                                 ", "Tektite"                                                            ), 			removed form pool cause grotto randomization isn't supported yet
//	ENTRANCE( 0x05C4	,"	Grottos	                                 ", "Forest Stage"                                                       ), 			removed form pool cause grotto randomization isn't supported yet
	ENTRANCE( 0x05C8	,"	Impa's House	                         ", "Roof entrance from Kakariko Village"                                ),
	ENTRANCE( 0x05CC	,"	Bottom of the Well	                     ", "???"                                                                ),
	ENTRANCE( 0x05D0	,"	Lon Lon Ranch Buildings	                 ", "Back Tower from Lon Lon Ranch"                                      ),
	ENTRANCE( 0x05D4	,"	Lon Lon Ranch	                         ", "Lon Lon Ranch Buildings Back Tower"                                 ),
	ENTRANCE( 0x05D8	,"	Ice Cavern	                             ", ""                                                                   ),
	ENTRANCE( 0x05DC	,"	Kakariko Village	                     ", "Impa's House Cow Exit"                                              ),
	ENTRANCE( 0x05E0	,"	Lost Woods	                             ", "Kokiri Forest Hyrule Exit"                                          ),
	ENTRANCE( 0x05E4	,"	Lon Lon Ranch Buildings	                 ", "Talon's House from Lose/Win Cucco Game"                             ),
	ENTRANCE( 0x05E8	,"	Kokiri Forest	                         ", "Deku Sprout Cutscene"                                               ),
	ENTRANCE( 0x05EC	,"	Spirit Temple Boss	                     ", "Inside Boss Map"                                                    ),
	ENTRANCE( 0x05F0	,"	Zelda's Courtyard	                     ", "From Triforce Legend CS"                                            ),
	ENTRANCE( 0x05F4	,"	Temple of Time	                         ", "Prelude Entrance"                                                   ),
	ENTRANCE( 0x05F8	,"	Gerudo Fortress	                         ", "Captured Second Time"                                               ),
//	ENTRANCE( 0x05FC	,"	Grottos	                                 ", "Cow"                                                                ), 			removed form pool cause grotto randomization isn't supported yet
	ENTRANCE( 0x0600	,"	Sacred Forest Meadow	                 ", "Minuet Warp"                                                        ),
	ENTRANCE( 0x0604	,"	Lake Hylia	                             ", "Serenade Warp"                                                      ),
	ENTRANCE( 0x0608	,"	Sacred Forest Meadow	                 ", "Forest Temple Boss Blue Warp"                                       ),
	ENTRANCE( 0x060C	,"	Lake Hylia	                             ", "Water Temple Boss Blue Warp"                                        ),
	ENTRANCE( 0x0610	,"	Desert Colossus	                         ", "Spirit Temple Boss Blue Warp"                                       ),
};

#define LOC_LEN sizeof(ref)/sizeof(ref[0])

const int loc_len = LOC_LEN;

__attribute__ ((aligned (4)))
 entry_t loc[LOC_LEN] = {};